language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh

script:
  - bash -ex .travis-opam.sh

env:
  - OCAML_VERSION=4.08 PACKAGE=cuid UPDATE_GCC_BINUTILS=1 BISECT_ENABLE=YES BISECT_SILENT=YES POST_INSTALL_HOOK="make report"
  - OCAML_VERSION=4.09 PACKAGE=cuid UPDATE_GCC_BINUTILS=1 BISECT_ENABLE=YES BISECT_SILENT=YES POST_INSTALL_HOOK="make report"
  - OCAML_VERSION=4.10 PACKAGE=cuid UPDATE_GCC_BINUTILS=1 BISECT_ENABLE=YES BISECT_SILENT=YES POST_INSTALL_HOOK="make report"
  - OCAML_VERSION=4.11 PACKAGE=cuid UPDATE_GCC_BINUTILS=1 BISECT_ENABLE=YES BISECT_SILENT=YES POST_INSTALL_HOOK="make report"

os:
  - linux
  - osx
