name: MacOS CI Workflow

on:
  push:
    branches:
      - stable
      - development
  pull_request:
    branches:
      - stable
      - development

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        package:
          - cuid
        os:
          - macos-latest
        ocaml-version:
          - 4.08.0
          - 4.08.1
          - 4.09.1
          - 4.10.1
          - 4.11.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add ${{ matrix.package }}.dev . --no-action
      - run: opam depext ${{ matrix.package }} --yes --with-test
      - run: opam install . --deps-only --with-doc --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
